[package]
name = "cc-tools-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "^0" }
strum = { version = "^0", features = ["derive"] }
strum_macros = { version = "^0" }
open = { version = "^3", optional = true }
serde = { version = "^1", features = ["derive"] }
chrono = { version = "^0" }
human_format = { version = "^1" }